DebugOptions = {  }
local CONSTANTS = require("logic.constants")
local Array = require("utils.classes.array")
local Set = require("utils.classes.set")
DebugOptions.ENABLED = false
if DebugOptions.ENABLED then
    DebugOptions.INITIAL_SCREEN = "title"
    DebugOptions.SEED = false
    DebugOptions.DEBUG_SLOW_MULTIPLIER = 0.1
    DebugOptions.DEFAULT_LEVEL_1_ITEMS = Array:new(CONSTANTS.STARTING_WEAPON)
    DebugOptions.FILL_EMPTY_SLOTS = false
    DebugOptions.STARTING_LEGENDARY = false
    DebugOptions.STARTING_SUFFIXED = false
    DebugOptions.STARTING_UPGRADE_LEVEL = false
    DebugOptions.ALL_LOOT_LEGENDARY = false
    DebugOptions.MAKE_ITEMS_FREQUENT = Set.EMPTY
    DebugOptions.MAKE_ENEMY_FREQUENT_AND_IN_FLOOR = false
    DebugOptions.MAKE_SUFFIX_FREQUENT = false
    DebugOptions.STARTING_FLOOR = 1
    DebugOptions.BANNED_ITEMS = Set:new()
    DebugOptions.DAMAGE_MULTIPLIER = 1
    DebugOptions.RESOURCES_MULTIPLIER = 1
    DebugOptions.NONPLAYER_HEALTH_MULTIPLIER = 1
    DebugOptions.COOLDOWN_MAXIMUM = false
    DebugOptions.PROCCING_SLOT = false
    DebugOptions.GENERATE_ROOMS = false
    DebugOptions.MAX_OUT_SCRAP = false
    DebugOptions.TEST_ELITE_TYPE = false
    DebugOptions.SINGLE_ROOM_SPAWN = false
    DebugOptions.FINAL_BOSS_RANGED = false
    DebugOptions.FINAL_BOSS_NO_SUMMON = false
    DebugOptions.HIDE_LOADING = false
    DebugOptions.ALL_DISCOVERED = false
    DebugOptions.MINIMAL_ROOMS = false
    DebugOptions.DISPLAY_CASTER_RESERVED = false
    DebugOptions.REPORT_SUFFIX_COUNT = false
    DebugOptions.REPORT_STAT_SPREAD = false
    DebugOptions.REPORT_VARIANCE_SPREAD = false
    DebugOptions.REPORT_ENEMY_STATS = false
    DebugOptions.REPORT_UNUSED_SOUNDS = false
    DebugOptions.LOG_DAMAGE_RESOLVED = false
    DebugOptions.FAIL_ON_WARNING = false
    DebugOptions.DISPLAY_BENCHMARKS = false
    DebugOptions.DRAW_TARGETING = false
    DebugOptions.DRAW_DEBUG_TEXT = false
else
    DebugOptions.INITIAL_SCREEN = "title"
    DebugOptions.SEED = false
    DebugOptions.DEBUG_SLOW_MULTIPLIER = 1
    DebugOptions.DEFAULT_LEVEL_1_ITEMS = Array:new(CONSTANTS.STARTING_WEAPON)
    DebugOptions.FILL_EMPTY_SLOTS = false
    DebugOptions.STARTING_LEGENDARY = false
    DebugOptions.STARTING_SUFFIXED = false
    DebugOptions.STARTING_UPGRADE_LEVEL = false
    DebugOptions.ALL_LOOT_LEGENDARY = false
    DebugOptions.MAKE_ITEMS_FREQUENT = Set.EMPTY
    DebugOptions.MAKE_ENEMY_FREQUENT_AND_IN_FLOOR = false
    DebugOptions.MAKE_SUFFIX_FREQUENT = false
    DebugOptions.STARTING_FLOOR = 1
    DebugOptions.BANNED_ITEMS = Set.EMPTY
    DebugOptions.DAMAGE_MULTIPLIER = 1
    DebugOptions.RESOURCES_MULTIPLIER = 1
    DebugOptions.NONPLAYER_HEALTH_MULTIPLIER = 1
    DebugOptions.COOLDOWN_MAXIMUM = false
    DebugOptions.PROCCING_SLOT = false
    DebugOptions.GENERATE_ROOMS = false
    DebugOptions.MAX_OUT_SCRAP = false
    DebugOptions.TEST_ELITE_TYPE = false
    DebugOptions.SINGLE_ROOM_SPAWN = false
    DebugOptions.FINAL_BOSS_RANGED = false
    DebugOptions.FINAL_BOSS_NO_SUMMON = false
    DebugOptions.HIDE_LOADING = false
    DebugOptions.ALL_DISCOVERED = false
    DebugOptions.MINIMAL_ROOMS = false
    DebugOptions.DISPLAY_CASTER_RESERVED = false
    DebugOptions.REPORT_SUFFIX_COUNT = false
    DebugOptions.REPORT_STAT_SPREAD = false
    DebugOptions.REPORT_VARIANCE_SPREAD = false
    DebugOptions.REPORT_ENEMY_STATS = false
    DebugOptions.REPORT_UNUSED_SOUNDS = false
    DebugOptions.LOG_DAMAGE_RESOLVED = false
    DebugOptions.FAIL_ON_WARNING = false
    DebugOptions.DISPLAY_BENCHMARKS = false
    DebugOptions.DRAW_TARGETING = false
    DebugOptions.DRAW_DEBUG_TEXT = false
end

return DebugOptions

