local WINDOW_LIMITS = {  }
require("port_settings")
WINDOW_LIMITS.WIDTH = 512
if PortSettings.IS_MOBILE then
    WINDOW_LIMITS.WIDTH = 600
end

WINDOW_LIMITS.HEIGHT = 320
WINDOW_LIMITS.DEFAULT_WIDTH = WINDOW_LIMITS.WIDTH * 2
WINDOW_LIMITS.DEFAULT_HEIGHT = WINDOW_LIMITS.HEIGHT * 2
if love.system.getOS() == "AuroraOS" then
    WINDOW_LIMITS.DEFAULT_WIDTH = WINDOW_LIMITS.WIDTH
    WINDOW_LIMITS.DEFAULT_HEIGHT = WINDOW_LIMITS.HEIGHT
end
return WINDOW_LIMITS

