local CONSTANTS = {  }
require("definitions.tags")
CONSTANTS.MAX_FLOORS = 25
CONSTANTS.STARTING_WEAPON = "weapons.sword"
CONSTANTS.MIN_FLOOR_MEDIUM_COMPLEXITY = 6
CONSTANTS.MIN_FLOOR_HIGH_COMPLEXITY = 11
CONSTANTS.HEALTH_PER_TURN = 0
CONSTANTS.MANA_PER_TURN = 0.02
CONSTANTS.ENEMY_ORB_CHANCE = 0.35
CONSTANTS.ELITE_HEALTH_MULTIPLIER = 1.75
CONSTANTS.ELITE_DAMAGE_MULTIPLIER = 1.25
CONSTANTS.ELITE_CHANCE_LOWEST = 0.25
CONSTANTS.ELITE_CHANCE_HIGHEST = 0.6
CONSTANTS.SCRAP_INITIAL = 0
CONSTANTS.SCRAP_COST_BASE = 5
CONSTANTS.SCRAP_COST_BASE_ACCESSORY = 5
CONSTANTS.SCRAP_COST_PER_LEVEL = 1
CONSTANTS.SCRAP_COST_LEGENDARY_MULTIPLIER = 2
CONSTANTS.SCRAP_SPENT_SELL_RATIO = 0.5
CONSTANTS.HEALTH_ORB_RESTORE = 1 / 7
CONSTANTS.ITEM_UPGRADE_LEVELS = 10
CONSTANTS.MAX_UPGRADE_INCREASE = 1.5
CONSTANTS.NEXT_ACTION_BUFF_DURATION = 5
CONSTANTS.MIN_COOLDOWN_ON_REDUCE = 3
CONSTANTS.MIN_DAMAGE_ON_REDUCE = 1
CONSTANTS.UPGRADE_LOWEST_MIN = 0
CONSTANTS.UPGRADE_LOWEST_MAX = 1
CONSTANTS.UPGRADE_HIGHEST_MIN = 3
CONSTANTS.UPGRADE_HIGHEST_MAX = 6
CONSTANTS.PRESUMED_INFINITE = 100000
CONSTANTS.MODIFIER_MIN_FLOOR = 2
CONSTANTS.MODIFIER_CHANCE_LOWEST = 0.25
CONSTANTS.MODIFIER_CHANCE_HIGHEST = 1
CONSTANTS.LEGENDARY_SELL_COST_MULTIPLIER = 3
CONSTANTS.DAMAGE_VARIANCE_LOW = 0.1
CONSTANTS.DAMAGE_VARIANCE_HIGH = 0.42
CONSTANTS.KNOCKBACK_DAMAGE_BASE = 10
CONSTANTS.KNOCKBACK_DAMAGE_VARIANCE = 0.2
CONSTANTS.PLAYER_PROJECTILE_SPEED = 3
CONSTANTS.PRODUCED_PROJECTILE_SPEED = 2
CONSTANTS.ENEMY_PROJECTILE_SPEED = 2
CONSTANTS.AVOID_COST_LOW = 1.02
CONSTANTS.AVOID_COST_MEDIUM_LOW = 2
CONSTANTS.AVOID_COST_MEDIUM = 8
CONSTANTS.AVOID_COST_MEDIUM_HIGH = 25
CONSTANTS.AVOID_COST_HIGH = 150
CONSTANTS.AVOID_COST_VERY_HIGH = 500
CONSTANTS.BAREHANDED_DAMAGE_MIN = 7
CONSTANTS.BAREHANDED_DAMAGE_MAX = 11
CONSTANTS.ENEMY_DAMAGE_BASE = 11
CONSTANTS.ENEMY_DAMAGE_PER_FLOOR = 0.825
CONSTANTS.ENEMY_HEALTH_BASE = 37
CONSTANTS.ENEMY_HEALTH_PER_FLOOR = 8.0
CONSTANTS.FLOOR_UNLOCK_COMPLEX = 11
CONSTANTS.ENEMY_DAMAGE_VARIANCE = (CONSTANTS.DAMAGE_VARIANCE_HIGH + CONSTANTS.DAMAGE_VARIANCE_LOW) / 2
CONSTANTS.ENEMY_ABILITY_VARIANCE = CONSTANTS.DAMAGE_VARIANCE_LOW
CONSTANTS.ABSOLUTE_MIN_FLOOR = { [Tags.SLOT_WEAPON] = 1, [Tags.SLOT_GLOVES] = 2, [Tags.SLOT_ARMOR] = 2, [Tags.SLOT_HELM] = 2, [Tags.SLOT_BOOTS] = 2, [Tags.SLOT_RING] = 4, [Tags.SLOT_AMULET] = 3 }
CONSTANTS.GUARANTEED_SLOTS = { [2] = Tags.SLOT_ARMOR, [3] = Tags.SLOT_GLOVES, [4] = Tags.SLOT_HELM, [5] = Tags.SLOT_AMULET, [6] = Tags.SLOT_BOOTS, [7] = Tags.SLOT_RING }
CONSTANTS.GUARANTEED_SLOTS_COUNT = 1
CONSTANTS.GUARANTEED_SLOTS_COUNT_AMULET = 2
CONSTANTS.DIFFICULTY_HEALTH_DIFFERENCE = 0.13
CONSTANTS.EASY_DAMAGE_MULTIPLIER = 0.8
CONSTANTS.DIFFICULTY_UPGRADE_DIFFERENCE = 1
Object:convert(CONSTANTS)
return CONSTANTS

