local ACTION_CONSTANTS = {  }
ACTION_CONSTANTS.WALK_DURATION = 0.225
ACTION_CONSTANTS.WAIT_DURATION = (ACTION_CONSTANTS.WALK_DURATION + 0.10) / 2
ACTION_CONSTANTS.EQUIP_DURATION = 0.35
ACTION_CONSTANTS.DEFAULT_BRACE_DURATION = 0.08
ACTION_CONSTANTS.DEFAULT_BRACE_DISTANCE = 0.2
ACTION_CONSTANTS.NEGATIVE_FADE_DURATION = 0.25
ACTION_CONSTANTS.STANDARD_FLASH_DURATION = 0.45
ACTION_CONSTANTS.SLOW_CAST_MULTIPLIER = 0.65
ACTION_CONSTANTS.MEDIUM_CAST_MULTIPLIER = 0.85
ACTION_CONSTANTS.MAJOR_CAST_CHARGE_DURATION = 0.275
ACTION_CONSTANTS.MINOR_CAST_CHARGE_DURATION = 0.2
Object:convert(ACTION_CONSTANTS)
return ACTION_CONSTANTS

